#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

cd "${repo_root}"

mkdir -p "${tmp_dir}/src" "${tmp_dir}/test/offline-apt"
cp -R "${repo_root}/src/offline-apt" "${tmp_dir}/src/"

run_expected_failure() {
  local name="$1"
  local expected="$2"
  local image="$3"
  local packages="$4"

  cat > "${tmp_dir}/test/offline-apt/scenarios.json" <<JSON
{
  "${name}": {
    "image": "${image}",
    "features": {
      "offline-apt": {
        "packages": "${packages}",
        "strict": true
      }
    }
  }
}
JSON

  cat > "${tmp_dir}/test/offline-apt/${name}.sh" <<'SH'
#!/usr/bin/env bash
set -euo pipefail
echo "this script should not run"
exit 1
SH
  chmod +x "${tmp_dir}/test/offline-apt/${name}.sh"

  set +e
  output="$(uv run devcontainer features test \
    --project-folder "${tmp_dir}" \
    --features offline-apt \
    --skip-autogenerated \
    --skip-duplicated \
    --filter "${name}" 2>&1)"
  status="$?"
  set -e

  if [ "${status}" -eq 0 ]; then
    echo "expected ${name} to fail, but it passed" >&2
    echo "${output}" >&2
    exit 1
  fi
  if ! printf '%s' "${output}" | grep -F "${expected}" >/dev/null 2>&1; then
    echo "expected ${name} output to contain: ${expected}" >&2
    echo "${output}" >&2
    exit 1
  fi
  echo "verified expected failure: ${name}"
}

run_expected_failure "wrong_debian" "only Debian trixie is supported" "debian:bookworm-slim" "jq"
run_expected_failure "wrong_ubuntu" "only Debian trixie is supported" "ubuntu:24.04" "jq"
run_expected_failure "bad_package_spec" "Invalid package spec" "debian:trixie-slim" "jq;curl example.com"
