#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
arch="${1:?usage: tools/run_feature_tests.sh <amd64|arm64>}"

cd "${repo_root}"
export DOCKER_DEFAULT_PLATFORM="linux/${arch}"

uv run offline-apt-feature render-test-scenarios --bundle bundle.yaml --arch "${arch}"
uv run devcontainer features test \
  --project-folder . \
  --features offline-apt \
  --skip-autogenerated \
  --skip-duplicated
